CREATE DATABASE IF NOT EXISTS tpFortnite;

use tpFortnite;

CREATE TABLE spawn
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(500) NOT NULL,
);


CREATE TABLE user
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
);
